# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewtryU.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(624, 477)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(606, 459))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.383892, y1:0.568, x2:1, y2:0.017, stop:0 rgba(229, 33, 101, 255), stop:1 rgba(255, 255, 255, 255));}\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Second_Frame = QtWidgets.QFrame(self.widget)
        self.Second_Frame.setStyleSheet("background-color: rgb(229, 33, 101);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 20px 20px 20px 20px;")
        self.Second_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Second_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Second_Frame.setObjectName("Second_Frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Second_Frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fork_btn = QtWidgets.QPushButton(self.Second_Frame, clicked=lambda: sys_fork())
        self.fork_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.fork_btn.setObjectName("fork_btn")
        self.verticalLayout_6.addWidget(self.fork_btn)
        self.pipe_btn = QtWidgets.QPushButton(self.Second_Frame, clicked=lambda: sys_pipe1())
        self.pipe_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.pipe_btn.setObjectName("pipe_btn")
        self.verticalLayout_6.addWidget(self.pipe_btn)
        self.twopipes_btn = QtWidgets.QPushButton(self.Second_Frame, clicked=lambda: sys_pipe2())
        self.twopipes_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.twopipes_btn.setObjectName("twopipes_btn")
        self.verticalLayout_6.addWidget(self.twopipes_btn)
        self.gridLayout_2.addWidget(self.Second_Frame, 2, 1, 1, 1)
        self.title_label = QtWidgets.QLabel(self.widget)
        self.title_label.setStyleSheet("font: 700 20pt \"Quicksand\";\n"
"color:rgb(13, 17, 55);")
        self.title_label.setObjectName("title_label")
        self.gridLayout_2.addWidget(self.title_label, 0, 0, 1, 4)
        self.Fourth_Frame = QtWidgets.QFrame(self.widget)
        self.Fourth_Frame.setStyleSheet("background-color: rgb(229, 33, 101);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 20px 20px 20px 20px;")
        self.Fourth_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Fourth_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Fourth_Frame.setObjectName("Fourth_Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Fourth_Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileLenght_btn = QtWidgets.QPushButton(self.Fourth_Frame, clicked=lambda: sys_sizefile())
        self.fileLenght_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.fileLenght_btn.setObjectName("fileLenght_btn")
        self.verticalLayout.addWidget(self.fileLenght_btn)
        self.frame = QtWidgets.QFrame(self.Fourth_Frame)
        self.frame.setStyleSheet("border-color: rgb(229, 33, 101);\n"
"background-color: rgb(185, 109, 152);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fgets_btn = QtWidgets.QPushButton(self.frame, clicked=lambda: sys_fgets())
        self.fgets_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.fgets_btn.setObjectName("fgets_btn")
        self.horizontalLayout.addWidget(self.fgets_btn)
        self.fputc_btn = QtWidgets.QPushButton(self.frame, clicked=lambda: sys_fputc())
        self.fputc_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.fputc_btn.setObjectName("fputc_btn")
        self.horizontalLayout.addWidget(self.fputc_btn)
        self.fputs_btn = QtWidgets.QPushButton(self.frame, clicked=lambda: sys_fputs())
        self.fputs_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.fputs_btn.setObjectName("fputs_btn")
        self.horizontalLayout.addWidget(self.fputs_btn)
        self.fgetc_btn = QtWidgets.QPushButton(self.frame, clicked=lambda: sys_fgetc())
        self.fgetc_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.fgetc_btn.setObjectName("fgetc_btn")
        self.horizontalLayout.addWidget(self.fgetc_btn)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout_2.addWidget(self.Fourth_Frame, 2, 3, 1, 1)
        self.First_Frame = QtWidgets.QFrame(self.widget)
        self.First_Frame.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(229, 33, 101);\n"
"border-radius: 20px 20px 20px 20px;")
        self.First_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.First_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.First_Frame.setObjectName("First_Frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.First_Frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.execlp_btn = QtWidgets.QPushButton(self.First_Frame, clicked=lambda: sys_execlp())
        self.execlp_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.execlp_btn.setObjectName("execlp_btn")
        self.verticalLayout_2.addWidget(self.execlp_btn)
        self.execv_btn = QtWidgets.QPushButton(self.First_Frame, clicked=lambda: sys_execv())
        self.execv_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.execv_btn.setObjectName("execv_btn")
        self.verticalLayout_2.addWidget(self.execv_btn)
        self.execvp_btn = QtWidgets.QPushButton(self.First_Frame, clicked=lambda: sys_execvp())
        self.execvp_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.execvp_btn.setObjectName("execvp_btn")
        self.verticalLayout_2.addWidget(self.execvp_btn)
        self.gridLayout_2.addWidget(self.First_Frame, 2, 0, 1, 1)
        self.Third_Frame = QtWidgets.QFrame(self.widget)
        self.Third_Frame.setStyleSheet("background-color: rgb(229, 33, 101);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 20px 20px 20px 20px;")
        self.Third_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Third_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Third_Frame.setObjectName("Third_Frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Third_Frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fseek_btn = QtWidgets.QPushButton(self.Third_Frame, clicked=lambda: sys_FseekExm())
        self.fseek_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.fseek_btn.setAutoDefault(True)
        self.fseek_btn.setDefault(False)
        self.fseek_btn.setObjectName("fseek_btn")
        self.verticalLayout_4.addWidget(self.fseek_btn)
        self.fseekEnd_btn = QtWidgets.QPushButton(self.Third_Frame, clicked=lambda: sys_Fseek_ENDExm())
        self.fseekEnd_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.fseekEnd_btn.setObjectName("fseekEnd_btn")
        self.verticalLayout_4.addWidget(self.fseekEnd_btn)
        self.ftell_btn = QtWidgets.QPushButton(self.Third_Frame, clicked=lambda: sys_FtellExm())
        self.ftell_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.ftell_btn.setObjectName("ftell_btn")
        self.verticalLayout_4.addWidget(self.ftell_btn)
        self.rewind_btn = QtWidgets.QPushButton(self.Third_Frame, clicked=lambda: sys_RewindExm())
        self.rewind_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.466, x2:1, y2:1, stop:0 rgba(97, 53, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0.192, y1:0.232409, x2:1, y2:1, stop:0 rgba(13, 17, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }\n"
"")
        self.rewind_btn.setObjectName("rewind_btn")
        self.verticalLayout_4.addWidget(self.rewind_btn)
        self.gridLayout_2.addWidget(self.Third_Frame, 2, 2, 1, 1)
        self.urchoice_lable = QtWidgets.QLabel(self.widget)
        self.urchoice_lable.setStyleSheet("font: 700 13pt \"Quicksand\";\n"
"color: rgb(13, 17, 55);")
        self.urchoice_lable.setObjectName("urchoice_lable")
        self.gridLayout_2.addWidget(self.urchoice_lable, 1, 0, 1, 1)
        #self.terminal_label = QtWidgets.QLabel(self.widget)
        self.terminal_label = QtWidgets.QTextEdit(self.widget)
        self.terminal_label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px 10px 10px 10px;")
        self.terminal_label.setText("")
        self.terminal_label.setObjectName("terminal_label")
        self.gridLayout_2.addWidget(self.terminal_label, 3, 0, 4, 4)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        def sys_fork():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 fork.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_execlp():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 execlp.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_execv():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 execv.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_execvp():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 execvp.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_fgetc():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 fgetc.py")
            p = output.read()
            self.terminal_label.insertPlainText(f' {p}')
            print("test")

        def sys_fgets():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 fgets.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_fputc():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 fputc.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_fputs():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 fputs.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")
        def sys_Fseek_ENDExm():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 FseekEND_Exm.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_FseekExm():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 FseekExm.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_FtellExm():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 FtellExm.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_pipe1():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 pipe1.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_pipe2():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 pipe2.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_RewindExm():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 RewindExm.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

        def sys_sizefile():
            # os. (["gcc", "date.c"])
            print("test")
            output = os.popen("python3 fileSize.py")
            p = output.read()
            self.terminal_label.insertPlainText(f'{p}')
            print("test")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fork_btn.setText(_translate("Dialog", "fork"))
        self.pipe_btn.setText(_translate("Dialog", "pipe"))
        self.twopipes_btn.setText(_translate("Dialog", "2pipes"))
        self.title_label.setText(_translate("Dialog", "Programmation système Virtual LAB"))
        self.fileLenght_btn.setText(_translate("Dialog", "File Lenght"))
        self.fgets_btn.setText(_translate("Dialog", "Fgets"))
        self.fputc_btn.setText(_translate("Dialog", "Fputc"))
        self.fputs_btn.setText(_translate("Dialog", "Fputs"))
        self.fgetc_btn.setText(_translate("Dialog", "Fgetc"))
        self.execlp_btn.setText(_translate("Dialog", "execlp"))
        self.execv_btn.setText(_translate("Dialog", "execv"))
        self.execvp_btn.setText(_translate("Dialog", "execvp"))
        self.fseek_btn.setText(_translate("Dialog", "Fseek"))
        self.fseekEnd_btn.setText(_translate("Dialog", "Fseek_end"))
        self.ftell_btn.setText(_translate("Dialog", "Ftell"))
        self.rewind_btn.setText(_translate("Dialog", "Rewind"))
        self.urchoice_lable.setText(_translate("Dialog", "fais ton choix"))
        self.terminal_label.insertPlainText(_translate("Dialog", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
